/*1*/
SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
LEFT OUTER JOIN DEPARTMENTS d ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID);

/*2*/
SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
RIGHT OUTER JOIN DEPARTMENTS d ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID);

/*3*/
SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
FULL OUTER JOIN DEPARTMENTS d ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID);

/*4*/
SELECT c.FIRST_NAME, c.LAST_NAME, e.EVENT_DATE, e.DESCRIPTION
FROM D_CLIENTS c
LEFT OUTER JOIN D_EVENTS e ON(c.CLIENT_NUMBER = e.CLIENT_NUMBER);

/*5*/
SELECT s.DESCRIPTION, a.SHIFT_ASSIGN_DATE
FROM F_SHIFTS s
LEFT OUTER JOIN F_SHIFT_ASSIGNMENTS a ON(s.CODE = a.CODE);