/*1*/
SELECT e.EMPLOYEE_ID AS "Employee", e.LAST_NAME AS "Emp#", e.MANAGER_ID AS "Manager", m.LAST_NAME AS "Mgr#"
FROM EMPLOYEES e
JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID);

/*2*/
SELECT e.EMPLOYEE_ID AS "Employee", e.LAST_NAME AS "Emp#", e.MANAGER_ID AS "Manager", m.LAST_NAME AS "Mgr#"
FROM EMPLOYEES e
LEFT OUTER JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID)
ORDER BY "Employee";

/*3*/
SELECT e.LAST_NAME AS "Employee", e.HIRE_DATE AS "Emp Hired", m.LAST_NAME AS "Manager", m.HIRE_DATE AS "Mgr Hired"
FROM EMPLOYEES e
JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID)
WHERE e.HIRE_DATE < m.HIRE_DATE;

/*4*/
SELECT LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 102
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

/*6*/
SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME)+((LEVEL-1)*2), '-')
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

/*7*/
SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME)+((LEVEL-1)*2), '-')
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
AND EMPLOYEE_ID != 102;