/*1*/
SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS;

/*2*/
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID, CITY
FROM DEPARTMENTS NATURAL JOIN LOCATIONS;

/*3*/
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID, CITY
FROM DEPARTMENTS NATURAL JOIN LOCATIONS
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50;