UPDATE  PRICE_HISTORY
SET     END_DATE = SYSDATE, END_TIME = SYSDATE
WHERE   ITM_NUMBER = 'im01101048' AND END_DATE IS NULL;

INSERT INTO PRICE_HISTORY(START_DATE, START_TIME, PRICE, END_DATE, END_TIME, ITM_NUMBER)
VALUES(SYSDATE, SYSDATE, 99.99, NULL, NULL, 'im01101048');

DELETE FROM CUSTOMERS_ADDRESSES WHERE id = 'ca0101';