/*1*/
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM F_STAFFS
WHERE SALARY BETWEEN 5.00 AND 10.00;

/*2*/
SELECT LOC_TYPE, COMMENTS
FROM D_VENUES
WHERE LOC_TYPE = 'Private Home';

/*3*/
SELECT first_name, last_name
FROM f_staffs
WHERE SALARY >= 20.00 AND SALARY <= 60.00;

/*4*/
SELECT TITLE
FROM D_CDS
WHERE TITLE LIKE '_a%';

/*5*/
SELECT *
FROM D_PARTNERS
WHERE AUTH_EXPENSE_AMT IS NULL;

/*6*/
SELECT LAST_NAME AS " Possible Candidates"
FROM EMPLOYEES
WHERE last_name LIKE '%s';

/*8*/
SELECT *
FROM d_songs
WHERE TYPE_CODE IN (1, 12, 77);