/*1*/
SELECT e.NAME, p.CODE
FROM D_EVENTS e, D_PACKAGES p,
WHERE (e.COST BETWEEN p.LOW_RANGE AND p.HIGH_RANGE);

/*2*/
SELECT e.LAST_NAME, e.SALARY, j.GRADE_LEVEL
FROM EMPLOYEE e, JOB_GRADES j
WHERE (e.SALARY BETWEEN j.LOWEST_SAL AND j.HIGHEST_SAL);

/*7*/
SELECT *
FROM F_CUSTOMERS c, F_ORDERS o
WHERE c.ID = o.CUST_ID(+);

/*8*/
SELECT e.LAST_NAME, e.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e, DEPARTMENTS d
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID(+);

/*9*/
SELECT e.LAST_NAME, e.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e, DEPARTMENTS d
WHERE e.DEPARTMENT_ID(+) = d.DEPARTMENT_ID;

/*10*/
SELECT e.employee id, e.last_name, d.location_id
FROM employees e, departments d
WHERE e.department_id = d.department_id(+);

/*11*/
SELECT c.title, t.SONG_ID
FROM D_CDS c, D_TRACK_LISTINGS t
WHERE c.CD_NUMBER = t.CD_NUMBER(+);