/*1*/
SELECT MONTHS_BETWEEN (EVENT_DATE, SYSDATE)
FROM D_EVENTS
WHERE ID = 105;

/*2*/
SELECT ROUND (MONTHS_BETWEEN ('6-Sep-2019', '21-Jun-2019')*30.5, 0) AS "Days"
FROM DUAL;

/*3*/
SELECT ROUND(MONTHS_BETWEEN ('31-Dec-2019', '1-Jan-2019')*30.5, 0) AS "Days"
FROM DUAL;

/*4*/
SELECT ROUND(SYSDATE, 'MONTH') AS "Rounded month", ROUND(SYSDATE, 'YEAR') AS "Rounded year", TRUNC(SYSDATE, 'MONTH') AS "Truncated month", TRUNC(SYSDATE, 'YEAR') AS "Truncated year"
FROM DUAL;

/*5*/
SELECT LAST_DAY('01-Jun-2005') AS "June 30"
FROM DUAL;

/*6*/
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, '19-Mar-1979')/12)
FROM F_STAFFS
WHERE ID = 9;

/*7*/
SELECT ADD_MONTHS(SYSDATE, 6) AS "Appointment"
FROM DUAL;

/*8*/
SELECT LAST_DAY(SYSDATE) AS "Deadline"
FROM DUAL;

/*9*/
SELECT MONTHS_BETWEEN('01-Jan-2020', '10-Dec-2019')
FROM DUAL;

/*10*/
SELECT NEXT_DAY('10-Dec-2019', 'Friday')
FROM DUAL;

/*1*/
SELECT ROUND(86.678, 2)
FROM DUAL;

/*2*/
SELECT UPPER(TITLE) AS "DJs on Demand Collections"
FROM D_CDS
WHERE cd_number BETWEEN 90 AND 91;

/*3*/
SELECT LOWER(LAST_NAME) || UPPER(SUBSTR(FIRST_NAME, 1, 1)) AS "User Passwords"
FROM D_PARTNERS;

/*4*/
SELECT 'HELLO ' || UPPER(SUBSTR('It’s a small world', 14, 5))
FROM DUAL;

/*5*/
SELECT REPLACE ('fiddledeedum', 'dum') || REPLACE('fiddledeedee', 'fiddle') AS "Nonsense"
FROM DUAL;

/*6*/
SELECT REPLACE ('Mississippi', 'i', '$')
FROM DUAL;

/*7*/
SELECT TRUNC(5332.342, -2)
FROM DUAL;

/*8*/
SELECT TRUNC(3.14159, 2)
FROM DUAL;

/*9*/
SELECT TRUNC(73.892, 1)
FROM DUAL;

/*10*/
SELECT NEXT_DAY(ADD_MONTHS(SYSDATE, 6), 'Friday') AS "Future"
FROM DUAL;

/*11*/
SELECT ADD_MONTHS(SYSDATE, 120) AS "Future"
FROM DUAL;

/*12*/
SELECT '29-Feb-2020' AS "Future"
FROM DUAL;

/*13*/
SELECT DESCRIPTION
FROM D_THEMES
WHERE DESCRIPTION LIKE '%ie%';

/*14*/
SELECT TITLE, YEAR
FROM D_CDS
WHERE YEAR BETWEEN 2000 AND 2002;

/*15*/
SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-Jan-1997' AND SYSDATE
ORDER BY HIRE_DATE DESC;