/*first suspect*/
SELECT NAME
FROM SUSPECTS
wHERE SEX = 'Male'
AND SCARS = 'Yes'
AND (HAIR_COLOR = 'Brown' OR HAIR_COLOR = 'Black')
AND FEET_SIZE = 'Large'
AND AGE BETWEEN 50 AND 60
AND GLASSES = 'Yes';

/*second suspect*/
SELECT NAME
FROM SUSPECTS
WHERE HAIR_COLOR = 'Red'
AND EYE_COLOR = 'Blue'
AND FEET_SIZE = 'Small'
AND TATTOOS = 'Yes'
AND AGE BETWEEN 35 AND 40;

/*THIRD SUSPECT*/
SELECT NAME
FROM SUSPECTS
WHERE HAIR_COLOR = 'Blonde'
AND EYE_COLOR = 'Blue'
AND GLASSES = 'No'
AND FEET_SIZE = 'Small'
AND TATTOOS = 'Yes'
AND AGE > 50;

/*FOURTH SUSPECT*/
SELECT NAME
FROM SUSPECTS
WHERE SEX = 'Female'
AND HEIGHT = 'Tall'
AND FACIAL_HAIR = 'Yes'
AND GLASSES = 'No'
AND SCARS = 'Yes'
AND TATTOOS = 'Yes'
AND FEET_SIZE = 'Large'
AND AGE < 30;