--PART 1
--1
SELECT FIRST_NAME, LAST_NAME
FROM F_CUSTOMERS
WHERE LENGTH(ZIP) < 10;

--3
SELECT NLV(AUTH_EXPENSE_AMT, 'Not Approved')
FROM D_PARTNERS;

--5
SELECT FIRST_NAME, LAST_NAME, BIRTHDATE, TO_CHAR(BIRTHDATE, Month) || TO_CHAR(SYSDATE, YYYY) AS 'SEND CARD
FROM F_STAFFS;

--7
SELECT FIRST_NAME, LAST_NAME, ROUND(MONTHS_BETWEEN(HIRE_DATE, SYSDATE)/12, 2)
FROM EMPLOYEES
WHERE ROUND(MONTHS_BETWEEN(HIRE_DATE, SYSDATE)/12, 2) > 10;

--8
SELECT SUBSTR(ADDRESS, LENGTH('123 Magnolia Road, Hudson, N.Y. 11220')-5) AS "OLD ZIP", SUBSTR(ADDRESS, LENGTH('123 Magnolia Road, Hudson, N.Y. 11220')-5) || '-2345' AS "NEW ZIP"
FROM D_VENUES
WHERE ID = 105;

--9
SELECT TO_CHAR(SYSDATE, YYYY), TO_CHAR(SYSDATE, MONTH), TRUNC(SYSDATE, YYYY), TRUNC(SYSDATE, MONTH)
FROM DUAL;

--10
SELECT TO_CHAR(END_DATE, DD-MONTH-YYYY)
FROM F_PROMOTIONAL_MENUES;

--11
SELECT SUBSTR(JOB_TITLE, 5) || '*'
FROM JOBS;

--13
SELECT *
FROM EMPLOYEES
WHERE ID = :EMPid;

--PART 2
--1
SELECT LOWER(FIRST_NAME)
FROM EMPLOYEES;

SELECT UPPER(FIRST_NAME)
FROM EMPLOYEES;

SELECT INTCAP(FIRST_NAME)
FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME, LAST_NAME)
FROM EMPLOYEES;

SELECT SUBSTR(FIRST_NAME, 2, 4)
FROM EMPLOYEES;

SELECT LENGTH(FIRST_NAME)
FROM EMPLOYEES;

SELECT INSTR(FIRST_NAME, 'a')
FROM EMPLOYEES;

SELECT LPAD(FIRST_NAME, 30, '*')
FROM EMPLOYEES;

SELECT RPAD(FIRST_NAME, 30, '*')
FROM EMPLOYEES;

SELECT TRIM(RIGHT '*' RPAD(FIRST_NAME, 30, '*'))
FROM EMPLOYEES;

SELECT REPLACE(RPAD(FIRST_NAME, 30, '*'), '*', '')
FROM EMPLOYEES;

SELECT ROUND(SALARY, 3)
FROM EMPLOYEES;

SELECT TRUNC(SALARY, 3)
FROM EMPLOYEES;

SELECT MOD(SALARY, 3)
FROM EMPLOYEES;

SELECT MONTHS_BETWEEN(HIRE_DATE, SYSDATE)
FROM EMPLOYEES;

SELECT ADD_MONTHS(HIRE_DATE, SYSDATE)
FROM EMPLOYEES;

SELECT NEXT_DAY(HIRE_DATE, 'Friday')
FROM EMPLOYEES;

SELECT LAST_DAY(HIRE_DATE)
FROM EMPLOYEES;

SELECT MONTHS_BETWEEN(HIRE_DATE, SYSDATE)
FROM EMPLOYEES;

--2
SELECT CD_NUMBER || TITLE
FROM D_CDS;

SELECT CONCAT(CD_NUMBER, TITLE)
FROM D_CDS;

--4
SELECT TO_CHAR(COST, '$0000.00')
FROM D_EVENTS;

--5
SELECT LPAD(ID, 2, '*')
FROM f_staffs;

--6
SELECT TO_DATE('15-Dec-1995', DD-Mon-YYY)
FROM DUAL;

--7
SELECT TO_CHAR('19-Jun-2004', DDth of month year)
FROM DUAL;

--8
SELECT SUBSTR('Oracle Academy', INSTR('Oracle Academy', ' '))
FROM DUAL;

--PART 3
--24 (47)
SELECT e.FIRST_NAME AS "Employee", e.LAST_NAME AS "Emp#", m.FIRST_NAME AS "Manager", m.LAST_NAME AS "Mgr#"
FROM EMPLOYEES e
JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID);

--25
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

--26
SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, E.SALARY, J.START_DATE, J.END_DATE, J.JOB_ID, D.DEPARTMENT_NAME, D.LOCATION_NAME
FROM EMPLOYEES E
JOIN JOB_HISTORY J
ON (E.EMPLOYEE_ID = J.EMPLOYEE_ID)
JOIN DEPARTMENT_ID D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

--PART 4
--1 (50)
CREATE TABLE o_employees AS
SELECT * FROM employees;

CREATE TABLE o_departments AS
SELECT * FROM departments;

CREATE TABLE o_jobs AS
SELECT * FROM jobs;

--2
INSERT INTO O_JOBS
VALUES(210, 'Human Resources', 4500, 5500);

--3
INSERT INTO o_employees(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID)
VALUES(210, 'Ramon', 'Sanchez', 'RSanchez', SYSDATE, 'HR_MAN', 210);

INSERT INTO o_employees(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID)
VALUES(211, 'Tai', 'Sugita', 'TSugita', SYSDATE, 'HR_MAN', 210);

INSERT INTO o_employees(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID)
VALUES(212, 'Alina', 'Arcos', 'AArcos', SYSDATE, 'HR_MAN', 210);

--4
INSERT INTO O_DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES(210, 'Human Resources', 211, 1700)

--5
UPDATE o_employees
SET PHONE_NUMBER = 360.509.7132
WHERE EMPLOYEE_ID = 210;

UPDATE o_employees
SET SALARY = 5100
WHERE EMPLOYEE_ID = 211;

UPDATE o_employees
SET SALARY = 5000
WHERE EMPLOYEE_ID = 210;

DELETE FROM O_EMPLOYEES WHERE ID = 212;

--PART 5
--16 (69)
CREATE TABLE your_initials_emp AS
SELECT * FROM employees;

ALTER TABLE your_initials_emp
ADD DEPARTMENT_NAME VARCHAR2(30);

--17
DROP o_employees;

SELECT * FROM O_EMPLOYEES;

SELECT * FROM GDRYTF;

RESTORE GDRYTF;