/*1*/
CREATE OR REPLACE VIEW view_copy_d_songs AS
SELECT TITLE, ARTIST
FROM copy_d_songs;

SELECT * FROM VIEW_COPY_D_SONGS;

/*2*/
DROP VIEW VIEW_COPY_D_SONGS;

SELECT * FROM VIEW_COPY_D_SONGS;

/*3*/
SELECT *
FROM 
    (SELECT LAST_NAME, SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC)
WHERE ROWNUM <= 3;

/*4*/
SELECT E.LAST_NAME, E.SALARY, E.DEPARTMENT_ID 
FROM
    (SELECT DD.DEPARTMENT_ID, MAX(EE.SALARY) max_dpt_sal
    FROM DEPARTMENTS DD
    JOIN EMPLOYEES EE
    ON EE.DEPARTMENT_ID = DD.DEPARTMENT_ID
    GROUP BY DD.DEPARTMENT_ID) D
JOIN EMPLOYEES E
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY = max_dpt_sal;

/*5*/
SELECT ROWNUM, FIRST_NAME, LAST_NAME
FROM F_STAFFS
ORDER BY SALARY;