/*2*/
CREATE VIEW VIEW_D_SONGS AS
SELECT ID, title AS "Song Title", artist
FROM D_SONGS
WHERE TYPE_CODE = 
    (SELECT CODE 
    FROM D_TYPES 
    WHERE DESCRIPTION = 'New Age');

/*4*/
CREATE OR REPLACE VIEW VIEW_D_SONGS AS
SELECT ID AS "id", title AS "Song Title", artist AS "Artist", type_code AS "Type Code"
FROM D_SONGS
WHERE TYPE_CODE = 
    (SELECT CODE 
    FROM D_TYPES 
    WHERE DESCRIPTION = 'New Age');
    
/*5*/
CREATE OR REPLACE VIEW VIEW_D_EVENTS AS
SELECT E.NAME AS "Event Name", E.EVENT_DATE AS "Event Date", T.DESCRIPTION AS "Description"
FROM D_EVENTS E JOIN D_THEMES T
ON E.THEME_CODE = T.CODE;

/*6*/
CREATE OR REPLACE VIEW VIEW_EMPLOYEES ("Department ID", "Maximum Salary", "Minimum Salary", "Average Salary") AS
SELECT DEPARTMENT_ID, MAX(NVL(SALARY, 0)), MIN(NVL(SALARY, 0)), ROUND(AVG(NVL(SALARY, 0)), 2)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;