/*2*/
SELECT TITLE
FROM D_SONGS
WHERE TYPE_CODE IN
    (SELECT CODE
    FROM D_TYPES
    WHERE DESCRIPTION IN('Jazz', 'Pop'));
    
/*3*/
SELECT LAST_NAME
FROM EMPLOYEES
WHERE SALARY IN
    (SELECT MIN(SALARY)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID);

/*4*/
SELECT LAST_NAME
FROM F_STAFFS
WHERE SALARY = 
    (SELECT MIN(SALARY)
    FROM F_STAFFS);
    
/*7*/
SELECT MIN(SALARY), DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) < 
    (SELECT MIN(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 50);
    
/*9*/
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
FROM EMPLOYEES
WHERE (DEPARTMENT_ID, MANAGER_ID) IN
    (SELECT DEPARTMENT_ID, MANAGER_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 141)
AND EMPLOYEE_ID != 141;

/*10*/
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
    (SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 141)
AND MANAGER_ID IN
    (SELECT MANAGER_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 141);