/*part 1*/
SELECT * 
FROM SALES_REPRESENTATIVES NATURAL JOIN SALES_REP_ADDRESSES;

SELECT ID, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, EMAIL, PHONE_NUMBER
FROM SALES_REPRESENTATIVES NATURAL JOIN SALES_REP_ADDRESSES;

/*part 2*/
SELECT ID, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, EMAIL, PHONE_NUMBER
FROM SALES_REPRESENTATIVES JOIN SALES_REP_ADDRESSES
USING (ID);

SELECT *
FROM ITEMS JOIN PRICE_HISTORY
USING (ITM_NUMBER);

/*part 3*/
SELECT C.CTR_NUMBER, C.FIRST_NAME, C.LAST_NAME, C.PHONE_NUMBER, C.EMAIL, S.ID, S.FIRST_NAME, S.LAST_NAME, S.EMAIL
FROM CUSTOMERS C JOIN SALES_REPRESENTATIVES S
ON (C.SRE_ID = S.ID);

/*PART 4*/
SELECT C.CTR_NUMBER, C.FIRST_NAME, C.LAST_NAME, C.PHONE_NUMBER, C.EMAIL, S.ID, S.FIRST_NAME, S.LAST_NAME, S.EMAIL, T.NAME
FROM CUSTOMERS C 
JOIN SALES_REPRESENTATIVES S
ON C.SRE_ID = S.ID
JOIN TEAMS T
ON T.ID = C.TEM_ID;

/*part 5*/
SELECT C.CTR_NUMBER, C.FIRST_NAME, C.LAST_NAME, C.PHONE_NUMBER, C.EMAIL, S.ID, S.FIRST_NAME, S.LAST_NAME, S.EMAIL, T.NAME
FROM CUSTOMERS C 
JOIN SALES_REPRESENTATIVES S
ON C.SRE_ID = S.ID
JOIN TEAMS T
ON T.ID = C.TEM_ID
WHERE C.CTR_NUMBER = 'c00001';

/*part 6*/
SELECT 'The cost of the ' || I.NAME || ' on this day was ' || P.PRICE
FROM ITEMS I
JOIN PRICE_HISTORY P
ON (I.ITM_NUMBER = 'im01101045') AND ('12-DEC-2016' BETWEEN P.START_DATE AND P.END_DATE);