/*project 1*/
SELECT NAME "Name", NUMBER_OF_PLAYERS "Players" FROM TEAMS ORDER BY NAME;
SELECT NAME "Name, NUMBER_OF_PLAYERS "Players" FROM TEAMS ORDER BY NUMBER_OF_PLAYERS DESC;
SELECT NAME "Team Name", NUMBER_OF_PLAYERS "Players" FROM TEAMS ORDER BY "Team Name" DESC;

/*project 2*/
/*part 1*/
SELECT ROWNUM AS "Order of membership", FIRST_NAME || ' ' || LAST_NAME AS "CUSTOMER NAME"
FROM CUSTOMERS
WHERE ROWNUM <= 3
ORDER BY CTR_NUMBER;

/*part 2*/
SELECT FIRST_NAME AS "FIRST NAME", LAST_NAME AS "LAST NAME"
FROM SALES_REPRESENTATIVES
WHERE COMMISSION_RATE = :COM_RATE
ORDER BY LAST_NAME;