/*1*/
SELECT COUNT(DISTINCT ID)
FROM D_SONGS;

/*2*/
SELECT COUNT(DISTINCT LOC_TYPE)
FROM D_VENUES;

/*3*/
SELECT COUNT(SONG_ID), COUNT(DISTINCT CD_NUMBER)
FROM D_TRACK_LISTINGS;

/*4*/
SELECT COUNT(PHONE)
FROM D_CLIENTS;

/*5*/
SELECT COUNT(AUTH_EXPENSE_AMT)
FROM D_PARTNERS;

/*7*/
SELECT ROUND(AVG(NVL(AUTH_EXPENSE_AMT, 100000)), 2)
FROM D_PARTNERS;