/*2*/
SELECT ROUND(AVG(COST),2)
FROM D_EVENTS;

/*3*/
SELECT ROUND(AVG(SALARY),2)
FROM F_STAFFS
WHERE MANAGER_ID = 19;

/*4*/
SELECT ROUND(SUM(SALARY),2)
FROM F_STAFFS
WHERE ID IN(12, 9);

/*5*/
SELECT MIN(SALARY), MAX(HIRE_DATE), MIN(LAST_NAME), MAX(LAST_NAME)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(50, 60);

/*9*/
SELECT ROUND(AVG(ORDER_TOTAL),2)
FROM F_ORDERS
WHERE ORDER_DATE IN('01-Jan-2002', '21-Dec-2002');

/*10*/
SELECT MAX(HIRE_DATE)
FROM EMPLOYEES;