/*1*/
CREATE TABLE COPY_F_FOOD_ITEMS
AS (SELECT * FROM F_FOOD_ITEMS);

UPDATE COPY_F_FOOD_ITEMS
SET PRICE = 3.75
WHERE FOOD_ITEM_NUMBER = 93;
UPDATE COPY_F_FOOD_ITEMS
SET PRICE = 1.20
WHERE FOOD_ITEM_NUMBER = 90;

/*2*/
CREATE TABLE COPY_F_STAFFS
AS (SELECT * FROM F_STAFFS);

UPDATE COPY_F_STAFFS
SET OVERTIME_RATE = NVL(OVERTIME_RATE, 0) + .85
WHERE ID = 12;
UPDATE COPY_F_STAFFS
SET OVERTIME_RATE = NVL(OVERTIME_RATE, 0) + .75
WHERE ID = 9;

/*3*/
CREATE TABLE copy_f_orders
AS (SELECT * FROM f_orders);

INSERT INTO COPY_d_cds (ORDER_NUMBER, ORDER_DATE, ORDER_TOTAL, CUST_ID, STAFF_ID)
VALUES (5680, TO_DATE('June 12, 2004','fmMonth dd, yyyy'), 159.78, 145, 9);
INSERT INTO COPY_d_cds (ORDER_NUMBER, ORDER_DATE, ORDER_TOTAL, CUST_ID, STAFF_ID)
VALUES (5691, TO_DATE('09-23-2004','mm-dd-yyyy'), 145.98, 225, 12);
INSERT INTO COPY_d_cds (ORDER_NUMBER, ORDER_DATE, ORDER_TOTAL, CUST_ID, STAFF_ID)
VALUES (5701, TO_DATE('July 4, 2004','fmMonth dd, yyyy'), 229.31, 230, 12);

/*4*/
CREATE TABLE copy_f_customers
AS (SELECT * FROM f_customers);

INSERT INTO copy_f_customers
VALUES (145, 'Katie', 'Hernandez', '92 Chico Way', 'Los Angeles', 'CA', 98008, '8586667641');
INSERT INTO copy_f_customers
VALUES (225, 'Daniel', 'Spode', '1923 Silverado', 'Denver', 'CO', 80219, '7193343523');
INSERT INTO copy_f_customers
VALUES (230, 'Adam', 'Zurn', '5 Admiral Way', 'Seattle', 'WA', 0, '4258879009');

/*5*/
UPDATE COPY_F_STAFFS
SET SALARY = 
    (SELECT SALARY
    FROM F_STAFFS
    WHERE ID = 9)
WHERE ID = 12;

/*6*/
INSERT IN COPY_F_STAFFS (ID, FIRST_NAME, LAST_NAME, BIRTHDATE, SALARY, STAFF_TYPE)
VALUES (25, 'Kai', 'Kim', TO_DATE('3-Nov-1988', 'fmdd-Mon-yyyy'), 6.75, 'Order Taker');

/*7*/
UPDATE COPY_F_STAFFS
SET MANAGER_ID = 
    (SELECT MANAGER_ID
    FROM F_STAFFS
    WHERE ID = 12)
WHERE ID = 25;

/*9*/
DELETE FROM COPY_F_STAFFS
WHERE ID = 25;

SELECT * FROM COPY_F_STAFFS;

/*10*/
CREATE TABLE lesson7_emp
AS (SELECT * FROM employees);

DELETE FROM lesson7_emp
WHERE EMPLOYEE_ID IN
    (SELECT DISTINCT EMPLOYEE_ID
    FROM JOB_HISTORY);