/*1*/
SELECT employee_id AS "Number", first_name, last_name
FROM employees
ORDER BY "Number";

/*2*/
SELECT TITLE
FROM D_CDS
ORDER BY YEAR, TITLE;

/*3*/
SELECT TITLE AS "Our Collection"
FROM d_cds
ORDER BY TITLE DESC;

/*4*/
SELECT FIRST_NAME, LAST_NAME, STUDENT_ID, PARKING_NUMBER
FROM STUDENTS
WHERE YEAR = 1
ORDER BY LAST_NAME, FIRST_NAME DESC;

/*5*/
SELECT DEPARTMENT_ID, LAST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID < 125
ORDER BY DEPARTMENT_ID DESC, LAST_NAME DESC;

/*11*/
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'St%';