/*5*/

CREATE ROLE MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLOYEES TO MANAGER;

CREATE ROLE CLERK;
GRANT SELECT, INSERT ON EMPLOYEES TO CLERK;

GRANT MANAGER TO SCOTT;

REVOKE DELETE ON EMPLOYEES FROM MANAGER;

