/*1*/
SELECT LOCATION_ID
FROM LOCATIONS JOIN DEPARTMENTS USING (LOCATION_ID)
WHERE LOCATION_ID = 1400;

/*2*/
SELECT SONG_ID, CD_NUMBER, TITLE, COMMENTS
FROM D_PLAY_LIST_ITEMS
JOIN D_TRACK_LISTINGS USING (SONG_ID)
JOIN D_CDS USING (CD_NUMBER);

/*3*/
SELECT CITY, DEPARTMENT_NAME, LOCATION_ID, DEPARTMENT_ID
FROM DEPARTMENTS
JOIN LOCATIONS USING (LOCATION_ID)
WHERE CITY = 'Seattle'
AND DEPARTMENT_ID IN (10, 20, 30);

/*4*/
SELECT COUNTRY_NAME, REGION_ID, REGION_NAME
FROM COUNTRIES
JOIN REGIONS USING (REGION_ID)
WHERE REGION_NAME = 'Americas';

/*5*/
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, JOB_ID, JOB_TITLE, MAX_SALARY
FROM EMPLOYEES
JOIN JOBS USING (JOB_ID)
WHERE MAX_SALARY > 1200;

/*6*/
SELECT JOB_TITLE, FIRST_NAME, LAST_NAME, EMAIL
FROM JOBS
JOIN EMPLOYEES USING (JOB_ID)
WHERE JOB_TITLE = 'Stock Clerk';

/*7*/
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.MANAGER_ID, m.FIRST_NAME, m.LAST_NAME
FROM EMPLOYEES e
JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID);

/*8*/
SELECT l.LOCATION_ID, l.CITY, d.DEPARTMENT_NAME
FROM LOCATIONS l
JOIN DEPARTMENTS d ON(l.LOCATION_ID = d.LOCATION_ID)
WHERE COUNTRY_ID = 'CA';

/*9*/
SELECT e.MANAGER_ID, e.DEPARTMENT_ID, d.DEPARTMENT_NAME, e.LAST_NAME
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d ON(e.DEPARTMENT_ID = d.DEPARTMENT_ID)
WHERE e.DEPARTMENT_ID IN (80, 90, 110, 190);

/*10*/
SELECT e.EMPLOYEE_ID, e.LAST_NAME, e.DEPARTMENT_ID, d.DEPARTMENT_NAME, e.HIRE_DATE
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON(e.DEPARTMENT_ID = d.DEPARTMENT_ID)
WHERE e.HIRE_DATE = '07-Jun-1994';