/*task 1*/
SELECT *
FROM AD_STUDENTS
ORDER BY REG_YEAR;

SELECT *
FROM AD_EXAM_RESULTS
ORDER BY STUDENT_ID, COURSE_ID;

SELECT *
FROM AD_STUDENT_ATTENDANCE
ORDER BY STUDENT_ID;

SELECT *
FROM AD_DEPARTMENTS
ORDER BY ID;

/*TASK 2*/
SELECT ROUND(NUM_DAYS_OFF/NUM_WORK_DAYS, 2)*100 AS "Percent of days out"
FROM AD_STUDENT_ATTENDANCE
ORDER BY "Percent out";

/*task 3*/
SELECT ROWNUM AS "TOP 5", STUDENT_ID
FROM AD_EXAM_RESULTS
WHERE ROWNUM <= 5
ORDER BY EXAM_GRADE DESC;

/*TASK 4*/
SELECT *
FROM AD_PARENT_INFORMATION
ORDER BY ID;