/*TASK 1*/
SELECT * FROM AD_ACADEMIC_SESSIONS;
SELECT * FROM AD_COURSES;
SELECT * FROM AD_DEPARTMENTS;
SELECT * FROM AD_EXAMS;
SELECT * FROM AD_EXAM_RESULTS;
SELECT * FROM AD_EXAM_TYPES;
SELECT * FROM AD_FACULTY;
SELECT * FROM AD_FACULTY_COURSE_DETAILS;
SELECT * FROM AD_FACULTY_LOGIN_DETAILS;
SELECT * FROM AD_PARENT_INFORMATION;
SELECT * FROM AD_STUDENTS;
SELECT * FROM AD_STUDENT_ATTENDANCE;
SELECT * FROM AD_STUDENT_COURSE_DETAILS;

SELECT STUDENT_ID, EXAM_GRADE FROM AD_EXAM_RESULTS;
SELECT NUM_WORK_DAYS, EXAM_ELIGIBILITY FROM AD_STUDENT_ATTENDANCE;
SELECT FACULTY_ID, LOGIN_DATE_TIME FROM AD_FACULTY_LOGIN_DETAILS;
SELECT NAME, HEAD FROM AD_DEPARTMENTS;

SELECT ID || ': FIRST NAME IS ' || FIRST_NAME FROM AD_STUDENTS;
SELECT * FROM AD_EXAM_TYPES;