/*1*/
/*I do not even fully know what the question is asking for*/
CREATE TABLE TIME_EX1
    (COLUMN1 TIMESTAMP
    COMLUMN2 TIMESTAMP WITH LOCAL TIME ZONE);
INSERT INTO TIME_EX1
VALUES (SYSTIMESTAMP, SYSTIMESTAMP);

CREATE TABLE TIME_EX2
    (COLUMN1 TIMESTAMP
    COMLUMN2 INTERVAL YEAR(3) TO MONTH);
INSERT INTO TIME_EX2
VALUES (SYSTIMESTAMP, SYSTIMESTAMP);

CREATE TABLE TIME_EX3
    (COLUMN1 TIMESTAMP
    COMLUMN2 INTERVAL DAY(3) TO SECOND);
INSERT INTO TIME_EX3
VALUES (SYSTIMESTAMP, SYSTIMESTAMP);

/*2*/
SELECT * FROM TIME_EX1;
SELECT * FROM TIME_EX2;
SELECT * FROM TIME_EX3;

