/*1*/
CREATE TABLE emp AS SELECT * FROM employees;
CREATE TABLE dept AS SELECT * FROM departments;

/*2*/
DESCRIBE USER_CONSTRAINTS;
/*C NAME, TYPE, */
DESCRIBE USER_CONS_COLUMNS;
/*C NAME, COLUMN NAME, POSITION*/

CREATE OR REPLACE VIEW REPORT1 AS
SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE, L.COLUMN_NAME, L.POSITION, C.TABLE_NAME
FROM USER_CONSTRAINTS C
JOIN USER_CONS_COLUMNS L
ON (C.CONSTRAINT_NAME = L.CONSTRAINT_NAME)
WHERE L.TABLE_NAME = "JOB_HISTORY"
AND C.CONSTRAINT_TYPE != 'N';

/*3*/
ALTER TABLE emp
ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY(EMPLOYEE_ID);

/*4*/
ALTER TABLE DEPT
ADD CONSTRAINT DEPT_DEPT_ID_PK PRIMARY KEY(DEPARTMENT_ID);

/*5*/
ALTER TABLE EMP
ADD CONSTRAINT EMP_DEPT_ID_FK
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPT (DEPARTMENT_ID)
ON DELETE CASCADE;

/*6*/
SELECT * FROM EMP;
DELETE FROM DEPT WHERE DEPARTMENT_ID = 10;
SELECT * FROM EMP;

/*7*/
SELECT E.LAST_NAME, E.SALARY, D.DEPARTMENT_ID, D.AVG_SALARY
FROM EMPLOYEES E
JOIN 
    (SELECT DEPARTMENT_ID, AVG(NVL(salary, 0)) AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE E.SALARY > D.AVG_SALARY;

/*8*/
CREATE OR REPLACE VIEW V2 AS
SELECT MAX(E.SALARY) "MAX SALARY", MIN(E.SALARY) "MIN SALARY", AVG(E.SALARY) "AVERAGE SALARY", D.DEPARTMENT_NAME "DEPARTMENT NAME"
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

/*9*/
CREATE OR REPLACE VIEW Dept_Managers_view AS
SELECT D.DEPARTMENT_NAME "Department name", SUBSTR(E.FIRST_NAME, 1, 1) "First initial", E.LAST_NAME "Last name"
FROM DEPARTMENTS D
JOIN EMPLOYEES E
ON(D.MANAGER_ID = E.EMPLOYEE_ID);

/*10*/
CREATE SEQUENCE ct_seq
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10000;
    
/*11*/
INSERT INTO emp(employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, commission_pct, manager_id, department_id)
VALUES (ct_seq.NEXTVAL, 'Kaare', 'Hansen', 'KHANSEN', '44965.832123', sysdate, 'SA_REP', 6500, null, 100, 20);

/*12*/
SELECT *
FROM user_tables
WHERE table_NAME like '%PRIV%';

/*13*/
GRANT SELECT ON EMP TO PUBLIC;

SELECT *
FROM user_tab_privs
WHERE table_name = 'EMP';

/*14*/
SELECT REGEXP_REPLACE('Oracle Academy9547d6905%&^ db apex','[^0-9]','') regexpreplace
FROM DUAL;

/*15*/
SELECT LENGTH(REGEXP_REPLACE('Oracle Academy9547d6905%&^ db apex','[^0-9]','')) regexpreplace
FROM DUAL;

/*16*/
SELECT REGEXP_REPLACE('Oracle Academy9547d6905%&^ db apex','[0-9]','') regexpreplace
FROM DUAL;

/*17*/
SELECT E.EMPLOYEE_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

/*18*/
SELECT E.EMPLOYEE_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

/*19*/
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY, COUNTRY_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND L.COUNTRY_ID = C.COUNTRY_ID;

/*20*/
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY, COUNTRY_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
AND D.LOCATION_ID = L.LOCATION_ID(+)
AND L.COUNTRY_ID = C.COUNTRY_ID(+);