/*1*/
CREATE TABLE emp AS SELECT * FROM employees;
CREATE TABLE dept AS SELECT * FROM departments;

/*2*/
DESCRIBE USER_CONSTRAINTS;
/*C NAME, TYPE, */
DESCRIBE USER_CONS_COLUMNS;
/*C NAME, COLUMN NAME, POSITION*/

CREATE OR REPLACE VIEW REPORT1 AS
SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE, L.COLUMN_NAME, L.POSITION, C.TABLE_NAME
FROM USER_CONSTRAINTS C
JOIN USER_CONS_COLUMNS L
ON (C.CONSTRAINT_NAME = L.CONSTRAINT_NAME)
WHERE L.TABLE_NAME = "JOB_HISTORY"
AND C.CONSTRAINT_TYPE != 'N';

/*3*/
ALTER TABLE emp
ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY(EMPLOYEE_ID);

/*4*/
ALTER TABLE DEPT
ADD CONSTRAINT DEPT_DEPT_ID_PK PRIMARY KEY(DEPARTMENT_ID);

/*5*/
ALTER TABLE EMP
ADD CONSTRAINT EMP_DEPT_ID_FK
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPT (DEPARTMENT_ID)
ON DELETE CASCADE;

/*6*/
SELECT * FROM EMP;
DELETE FROM DEPT WHERE DEPARTMENT_ID = 10;
SELECT * FROM EMP;

/*7*/
SELECT E.LAST_NAME, E.SALARY, D.DEPARTMENT_ID, D.AVG_SALARY
FROM EMPLOYEES E
JOIN 
    (SELECT DEPARTMENT_ID, AVG(NVL(salary, 0)) AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID) D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE E.SALARY > D.AVG_SALARY;