/*2*/
SELECT LAST_NAME
FROM F_STAFFS
WHERE LAST_NAME LIKE '%e%' AND LAST_NAME LIKE '%i%';

/*3*/
SELECT *
FROM F_STAFFS
WHERE SALARY > 6.50 AND STAFF_TYPE != 'Order Taker';

/*4*/
SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'D%' AND LAST_NAME LIKE '%e%' AND LAST_NAME LIKE '%a%';

/*7*/
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE (HIRE_DATE BETWEEN '01-Jun-1998' AND '31-May-1999') AND (SALARY < 8000) AND (LAST_NAME LIKE '%en%');

/*8*/
SELECT EMAIL
FROM EMPLOYEES
WHERE (HIRE_DATE >= '01-Jan-1996') AND (SALARY > 9000) AND (COMMISSION_PCT IS NULL);